
/*
 * 
 */

package org.openehealth.ipf.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.11
 * Tue Jan 18 15:26:11 CET 2011
 * Generated source version: 2.2.11
 * 
 */


@WebServiceClient(name = "ORMRegistry_Service", 
                  wsdlLocation = "file:/D:/Documents%20and%20Settings/100026806/ormregistry/src/main/resources/wsdl/ORMRegistry.wsdl",
                  targetNamespace = "http://gehcit.com/platform/cws/ORMRegistry") 
public class ORMRegistryService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://gehcit.com/platform/cws/ORMRegistry", "ORMRegistry_Service");
    public final static QName ORMRegistryPortSoap12 = new QName("http://gehcit.com/platform/cws/ORMRegistry", "ORMRegistry_Port_Soap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Documents%20and%20Settings/100026806/ormregistry/src/main/resources/wsdl/ORMRegistry.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/Documents%20and%20Settings/100026806/ormregistry/src/main/resources/wsdl/ORMRegistry.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ORMRegistryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ORMRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ORMRegistryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ORMRegistry
     */
    @WebEndpoint(name = "ORMRegistry_Port_Soap12")
    public ORMRegistry getORMRegistryPortSoap12() {
        return super.getPort(ORMRegistryPortSoap12, ORMRegistry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ORMRegistry
     */
    @WebEndpoint(name = "ORMRegistry_Port_Soap12")
    public ORMRegistry getORMRegistryPortSoap12(WebServiceFeature... features) {
        return super.getPort(ORMRegistryPortSoap12, ORMRegistry.class, features);
    }

}
