package org.openehealth.ipf.ws;

import org.openehealth.ipf.ws.stub.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.11
 * Tue Jan 18 15:26:11 CET 2011
 * Generated source version: 2.2.11
 * 
 */
 
@WebService(targetNamespace = "http://gehcit.com/platform/cws/ORMRegistry", name = "ORMRegistry")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ORMRegistry {

    @WebResult(name = "ReviseORMResponse", targetNamespace = "http://gehcit.com/platform/cws/orm/types", partName = "body")
    @WebMethod(action = "http://gehcit.com/platform/cws/ORMRegistry/reviseORMRequest")
    public ReviseORMResponse reviseORMRequest(
        @WebParam(partName = "body", name = "ReviseORMRequest", targetNamespace = "http://gehcit.com/platform/cws/orm/types")
        ReviseORMRequest body
    );

    @WebResult(name = "DeleteORMResponse", targetNamespace = "http://gehcit.com/platform/cws/orm/types", partName = "body")
    @WebMethod(action = "http://gehcit.com/platform/cws/ORMRegistry/deleteORMRequest")
    public DeleteORMResponse deleteORMRequest(
        @WebParam(partName = "body", name = "DeleteORMRequest", targetNamespace = "http://gehcit.com/platform/cws/orm/types")
        DeleteORMRequest body
    );
}
